// Auto-generated by tools/muveez-curation/merge-batch10.js — do not hand-edit.
// One answer per calendar day-of-year, same indexing as images/<day>.jpg
// (see index.js's dayOfYear() usage).
export const ANSWERS_366 = [
  'Nixon', // day 1: Nixon
  'Aladdin', // day 2: Aladdin
  'Moana', // day 3: Moana
  'The Spy Who Loved Me', // day 4: The Spy Who Loved Me
  'Minority Report', // day 5: Minority Report
  'The Godfather', // day 6: The Godfather
  'Clueless', // day 7: Clueless
  'Starsky & Hutch', // day 8: Starsky & Hutch
  'Daredevil', // day 9: Daredevil
  'To Kill a Mockingbird', // day 10: To Kill a Mockingbird
  'Dances with Wolves', // day 11: Dances with Wolves
  'Logan', // day 12: Logan
  'The Boat That Rocked', // day 13: The Boat That Rocked
  'Superman', // day 14: Superman
  'No Country for Old Men', // day 15: No Country for Old Men
  'Babe', // day 16: Babe
  'Mary Poppins Returns', // day 17: Mary Poppins Returns
  'Paddington', // day 18: Paddington
  'Ford v Ferrari', // day 19: Ford v Ferrari
  'The Goonies', // day 20: The Goonies
  'Jaws', // day 21: Jaws
  'Alien', // day 22: Alien
  'Poltergeist', // day 23: Poltergeist
  'Django Unchained', // day 24: Django Unchained
  'Napoleon', // day 25: Napoleon
  'Planet of the Apes', // day 26: Planet of the Apes
  'Ratatouille', // day 27: Ratatouille
  'Ocean\'s 8', // day 28: Ocean's 8
  'Brokeback Mountain', // day 29: Brokeback Mountain
  'War of the Worlds', // day 30: War of the Worlds
  'Citizen Kane', // day 31: Citizen Kane
  'Ferris Bueller\'s Day Off', // day 32: Ferris Bueller's Day Off
  'The King\'s Speech', // day 33: The King's Speech
  '500 Days of Summer', // day 34: 500 Days of Summer
  'WarGames', // day 35: WarGames
  'Mission: Impossible', // day 36: Mission: Impossible
  'Duck Soup', // day 37: Duck Soup
  'When Harry Met Sally...', // day 38: When Harry Met Sally...
  'Luca', // day 39: Luca
  'The Santa Clause', // day 40: The Santa Clause
  'Wonder Woman', // day 41: Wonder Woman
  'Baby Driver', // day 42: Baby Driver
  'Guardians of the Galaxy', // day 43: Guardians of the Galaxy
  'The NeverEnding Story', // day 44: The NeverEnding Story
  'Frozen', // day 45: Frozen
  'Oppenheimer', // day 46: Oppenheimer
  'King Kong', // day 47: King Kong
  'The Italian Job', // day 48: The Italian Job
  'The Usual Suspects', // day 49: The Usual Suspects
  'Frankenstein', // day 50: Frankenstein
  'Lawrence of Arabia', // day 51: Lawrence of Arabia
  'Romeo and Juliet', // day 52: Romeo and Juliet
  'Desperately Seeking Susan', // day 53: Desperately Seeking Susan
  'Little Miss Sunshine', // day 54: Little Miss Sunshine
  'To Sir, with Love', // day 55: To Sir, with Love
  'Midnight Cowboy', // day 56: Midnight Cowboy
  'Chicago', // day 57: Chicago
  'Get Shorty', // day 58: Get Shorty
  'My Fair Lady', // day 59: My Fair Lady
  'Bridget Jones\'s Diary', // day 60: Bridget Jones's Diary
  'A Few Good Men', // day 61: A Few Good Men
  'In Bruges', // day 62: In Bruges
  'Full Metal Jacket', // day 63: Full Metal Jacket
  'Top Gun', // day 64: Top Gun
  'The Martian', // day 65: The Martian
  'Star Wars', // day 66: Star Wars
  '10 Things I Hate About You', // day 67: 10 Things I Hate About You
  'Working Girl', // day 68: Working Girl
  'Field of Dreams', // day 69: Field of Dreams
  'Beauty and the Beast', // day 70: Beauty and the Beast
  'The Good, the Bad and the Ugly', // day 71: The Good, the Bad and the Ugly
  'Platoon', // day 72: Platoon
  'Return of the Jedi', // day 73: Return of the Jedi
  'No Time to Die', // day 74: No Time to Die
  'Wonka', // day 75: Wonka
  'The Sting', // day 76: The Sting
  'Notting Hill', // day 77: Notting Hill
  'The Karate Kid', // day 78: The Karate Kid
  'A Clockwork Orange', // day 79: A Clockwork Orange
  'Born on the Fourth of July', // day 80: Born on the Fourth of July
  'War Horse', // day 81: War Horse
  'The Departed', // day 82: The Departed
  'Walk the Line', // day 83: Walk the Line
  'Titanic', // day 84: Titanic
  'Beverly Hills Cop', // day 85: Beverly Hills Cop
  'Knocked Up', // day 86: Knocked Up
  'Inception', // day 87: Inception
  'Gone Girl', // day 88: Gone Girl
  '101 Dalmatians', // day 89: 101 Dalmatians
  'The Illusionist', // day 90: The Illusionist
  'Lethal Weapon', // day 91: Lethal Weapon
  'Se7en', // day 92: Se7en
  'All the President\'s Men', // day 93: All the President's Men
  'Cars', // day 94: Cars
  'F1', // day 95: F1
  'Elemental', // day 96: Elemental
  'Charlotte\'s Web', // day 97: Charlotte's Web
  'Forrest Gump', // day 98: Forrest Gump
  'Austin Powers', // day 99: Austin Powers
  'Scarface', // day 100: Scarface
  'Pulp Fiction', // day 101: Pulp Fiction
  'About Time', // day 102: About Time
  'Gentlemen Prefer Blondes', // day 103: Gentlemen Prefer Blondes
  'Coraline', // day 104: Coraline
  'A Fistful of Dollars', // day 105: A Fistful of Dollars
  'Cool Runnings', // day 106: Cool Runnings
  'Batman Returns', // day 107: Batman Returns
  'National Lampoon\'s Vacation', // day 108: National Lampoon's Vacation
  'Jumanji', // day 109: Jumanji
  'Killers of the Flower Moon', // day 110: Killers of the Flower Moon
  'A Quiet Place', // day 111: A Quiet Place
  'A Star Is Born', // day 112: A Star Is Born
  'The Fugitive', // day 113: The Fugitive
  'Godzilla', // day 114: Godzilla
  'The Lion King', // day 115: The Lion King
  'Robin Hood', // day 116: Robin Hood
  'Bullitt', // day 117: Bullitt
  'Encanto', // day 118: Encanto
  'Grease', // day 119: Grease
  'The Graduate', // day 120: The Graduate
  'Black Hawk Down', // day 121: Black Hawk Down
  'Crocodile Dundee', // day 122: Crocodile Dundee
  'WALL-E', // day 123: WALL-E
  'The Bourne Identity', // day 124: The Bourne Identity
  'Kramer vs. Kramer', // day 125: Kramer vs. Kramer
  'The Wild One', // day 126: The Wild One
  'The Mask', // day 127: The Mask
  'The Wrestler', // day 128: The Wrestler
  'Knives Out', // day 129: Knives Out
  'Gunfight at the O.K. Corral', // day 130: Gunfight at the O.K. Corral
  'Apocalypse Now', // day 131: Apocalypse Now
  'Juno', // day 132: Juno
  'Doctor Strange', // day 133: Doctor Strange
  'La La Land', // day 134: La La Land
  'Young Frankenstein', // day 135: Young Frankenstein
  'Rocky', // day 136: Rocky
  'Gangs of New York', // day 137: Gangs of New York
  'The Hangover', // day 138: The Hangover
  'Deadpool', // day 139: Deadpool
  'Divergent', // day 140: Divergent
  'The Mummy', // day 141: The Mummy
  'Twister', // day 142: Twister
  'School of Rock', // day 143: School of Rock
  'Jurassic Park', // day 144: Jurassic Park
  'Footloose', // day 145: Footloose
  'The Shawshank Redemption', // day 146: The Shawshank Redemption
  'The Grand Budapest Hotel', // day 147: The Grand Budapest Hotel
  'Evita', // day 148: Evita
  'Casino Royale', // day 149: Casino Royale
  'Lucy', // day 150: Lucy
  'Kung Fu Panda', // day 151: Kung Fu Panda
  'The Incredibles', // day 152: The Incredibles
  'Dirty Dancing', // day 153: Dirty Dancing
  'Saturday Night Fever', // day 154: Saturday Night Fever
  'Spartacus', // day 155: Spartacus
  'Clear and Present Danger', // day 156: Clear and Present Danger
  'Batman', // day 157: Batman
  'Love Story', // day 158: Love Story
  'National Treasure', // day 159: National Treasure
  'The Client', // day 160: The Client
  'Eat Pray Love', // day 161: Eat Pray Love
  'Oliver Twist', // day 162: Oliver Twist
  'Ant-Man', // day 163: Ant-Man
  'Billy Elliot', // day 164: Billy Elliot
  'How to Train Your Dragon', // day 165: How to Train Your Dragon
  'The Silence of the Lambs', // day 166: The Silence of the Lambs
  'The Running Man', // day 167: The Running Man
  'The Gentlemen', // day 168: The Gentlemen
  'West Side Story', // day 169: West Side Story
  'Some Like It Hot', // day 170: Some Like It Hot
  'Zootopia', // day 171: Zootopia
  'Million Dollar Baby', // day 172: Million Dollar Baby
  'Hercules', // day 173: Hercules
  'Ice Age', // day 174: Ice Age
  'Elvis', // day 175: Elvis
  'Mad Max', // day 176: Mad Max
  'The Big Lebowski', // day 177: The Big Lebowski
  'Lightyear', // day 178: Lightyear
  'Mrs. Doubtfire', // day 179: Mrs. Doubtfire
  'The Princess Diaries', // day 180: The Princess Diaries
  'Legally Blonde', // day 181: Legally Blonde
  'The Shining', // day 182: The Shining
  'Lara Croft: Tomb Raider', // day 183: Lara Croft: Tomb Raider
  'Hooper', // day 184: Hooper
  'Despicable Me', // day 185: Despicable Me
  'Home Alone', // day 186: Home Alone
  'Shakespeare in Love', // day 187: Shakespeare in Love
  'Green Book', // day 188: Green Book
  'Dumbo', // day 189: Dumbo
  'Twilight', // day 190: Twilight
  'Goodfellas', // day 191: Goodfellas
  'Parasite', // day 192: Parasite
  'Coming to America', // day 193: Coming to America
  'The Social Network', // day 194: The Social Network
  'Dr. No', // day 195: Dr. No
  'Crazy Rich Asians', // day 196: Crazy Rich Asians
  'Space Jam', // day 197: Space Jam
  'Freaky Friday', // day 198: Freaky Friday
  'Pitch Perfect', // day 199: Pitch Perfect
  'James and the Giant Peach', // day 200: James and the Giant Peach
  'Blue Velvet', // day 201: Blue Velvet
  'The Rock', // day 202: The Rock
  'The Fox and the Hound', // day 203: The Fox and the Hound
  'There Will Be Blood', // day 204: There Will Be Blood
  'The French Connection', // day 205: The French Connection
  'The Wolverine', // day 206: The Wolverine
  'Ace Ventura: Pet Detective', // day 207: Ace Ventura: Pet Detective
  'Black Swan', // day 208: Black Swan
  'The Little Mermaid', // day 209: The Little Mermaid
  'Aladdin', // day 210: Aladdin
  'The Hunger Games', // day 211: The Hunger Games
  'Around the World in 80 Days', // day 212: Around the World in 80 Days
  'The Sound of Music', // day 213: The Sound of Music
  'The Hustler', // day 214: The Hustler
  'Bohemian Rhapsody', // day 215: Bohemian Rhapsody
  'Serendipity', // day 216: Serendipity
  'Captain America', // day 217: Captain America
  'Basic Instinct', // day 218: Basic Instinct
  'Whiplash', // day 219: Whiplash
  'The Addams Family', // day 220: The Addams Family
  'Gladiator', // day 221: Gladiator
  'The Irishman', // day 222: The Irishman
  'Bend It Like Beckham', // day 223: Bend It Like Beckham
  'Avatar', // day 224: Avatar
  'The 40-Year-Old Virgin', // day 225: The 40-Year-Old Virgin
  'Tootsie', // day 226: Tootsie
  'The Color Purple', // day 227: The Color Purple
  'Enchanted', // day 228: Enchanted
  'Turning Red', // day 229: Turning Red
  'Poor Things', // day 230: Poor Things
  'Ghostbusters', // day 231: Ghostbusters
  'Sister Act', // day 232: Sister Act
  'Goldfinger', // day 233: Goldfinger
  'Rear Window', // day 234: Rear Window
  'Madagascar', // day 235: Madagascar
  'Inside Out', // day 236: Inside Out
  'Beetlejuice', // day 237: Beetlejuice
  'Wilde', // day 238: Wilde
  'Lincoln', // day 239: Lincoln
  'The Full Monty', // day 240: The Full Monty
  'The Breakfast Club', // day 241: The Breakfast Club
  'The Notebook', // day 242: The Notebook
  'Pocahontas', // day 243: Pocahontas
  'Spy Kids', // day 244: Spy Kids
  'Groundhog Day', // day 245: Groundhog Day
  'Jerry Maguire', // day 246: Jerry Maguire
  'The Avengers', // day 247: The Avengers
  'Lady and the Tramp', // day 248: Lady and the Tramp
  'Monsters, Inc.', // day 249: Monsters, Inc.
  'Much Ado About Nothing', // day 250: Much Ado About Nothing
  'High Noon', // day 251: High Noon
  'The Death of Stalin', // day 252: The Death of Stalin
  'True Lies', // day 253: True Lies
  'A Hard Day\'s Night', // day 254: A Hard Day's Night
  'The Dukes of Hazzard', // day 255: The Dukes of Hazzard
  'Saving Private Ryan', // day 256: Saving Private Ryan
  'Edward Scissorhands', // day 257: Edward Scissorhands
  'Ghost', // day 258: Ghost
  'The Wolf of Wall Street', // day 259: The Wolf of Wall Street
  'Minions', // day 260: Minions
  'Get Carter', // day 261: Get Carter
  'Dumb and Dumber', // day 262: Dumb and Dumber
  'Soul', // day 263: Soul
  'Tarzan', // day 264: Tarzan
  'The Jungle Book', // day 265: The Jungle Book
  'Moulin Rouge!', // day 266: Moulin Rouge!
  'Die Hard', // day 267: Die Hard
  'Blue Jasmine', // day 268: Blue Jasmine
  'Night at the Museum', // day 269: Night at the Museum
  'The Wedding Singer', // day 270: The Wedding Singer
  'Happy Feet', // day 271: Happy Feet
  'Amadeus', // day 272: Amadeus
  'Philadelphia', // day 273: Philadelphia
  'Chariots of Fire', // day 274: Chariots of Fire
  'Live and Let Die', // day 275: Live and Let Die
  'There\'s Something About Mary', // day 276: There's Something About Mary
  'Fantasia', // day 277: Fantasia
  'King Kong', // day 278: King Kong
  'Trainspotting', // day 279: Trainspotting
  'Spider-Man 2', // day 280: Spider-Man 2
  'Patriot Games', // day 281: Patriot Games
  'Mary Poppins', // day 282: Mary Poppins
  'A Bug\'s Life', // day 283: A Bug's Life
  'Braveheart', // day 284: Braveheart
  'The Magnificent Seven', // day 285: The Magnificent Seven
  'In the Heat of the Night', // day 286: In the Heat of the Night
  'The Exorcist', // day 287: The Exorcist
  'The Color of Money', // day 288: The Color of Money
  'Big Hero 6', // day 289: Big Hero 6
  'Gone with the Wind', // day 290: Gone with the Wind
  '50 First Dates', // day 291: 50 First Dates
  'Wall Street', // day 292: Wall Street
  'Gremlins', // day 293: Gremlins
  'Arthur', // day 294: Arthur
  'Scrooged', // day 295: Scrooged
  'Gravity', // day 296: Gravity
  'Mulan', // day 297: Mulan
  'Annie Hall', // day 298: Annie Hall
  'Black Panther', // day 299: Black Panther
  'Ocean\'s Eleven', // day 300: Ocean's Eleven
  'Alfie', // day 301: Alfie
  'Happy Gilmore', // day 302: Happy Gilmore
  'Matilda', // day 303: Matilda
  'Nope', // day 304: Nope
  'Moonraker', // day 305: Moonraker
  'Judge Dredd', // day 306: Judge Dredd
  'Brave', // day 307: Brave
  'Black Widow', // day 308: Black Widow
  '12 Years a Slave', // day 309: 12 Years a Slave
  'Gandhi', // day 310: Gandhi
  'Shark Tale', // day 311: Shark Tale
  'Flashdance', // day 312: Flashdance
  'Men in Black', // day 313: Men in Black
  'Zoolander', // day 314: Zoolander
  'Bill & Ted\'s Excellent Adventure', // day 315: Bill & Ted's Excellent Adventure
  'Predator', // day 316: Predator
  'Now You See Me', // day 317: Now You See Me
  'Jurassic World', // day 318: Jurassic World
  'Back to the Future', // day 319: Back to the Future
  'The Lion King', // day 320: The Lion King
  'Puss in Boots', // day 321: Puss in Boots
  'Star Trek', // day 322: Star Trek
  'Little Women', // day 323: Little Women
  'GoldenEye', // day 324: GoldenEye
  'Speed', // day 325: Speed
  'Wicked', // day 326: Wicked
  'Johnny English', // day 327: Johnny English
  'Cinderella', // day 328: Cinderella
  'The Matrix', // day 329: The Matrix
  'Breakfast at Tiffany\'s', // day 330: Breakfast at Tiffany's
  'Wreck-It Ralph', // day 331: Wreck-It Ralph
  'The Last Samurai', // day 332: The Last Samurai
  'Meet the Parents', // day 333: Meet the Parents
  'Toy Story', // day 334: Toy Story
  'Bambi', // day 335: Bambi
  'The Jungle Book', // day 336: The Jungle Book
  'Shrek', // day 337: Shrek
  'Ben-Hur', // day 338: Ben-Hur
  'Good Will Hunting', // day 339: Good Will Hunting
  'Twins', // day 340: Twins
  'I Am Legend', // day 341: I Am Legend
  'Wayne\'s World', // day 342: Wayne's World
  'Free Willy', // day 343: Free Willy
  'Labyrinth', // day 344: Labyrinth
  'Jojo Rabbit', // day 345: Jojo Rabbit
  'The Pelican Brief', // day 346: The Pelican Brief
  'Coco', // day 347: Coco
  'You\'ve Got Mail', // day 348: You've Got Mail
  'Peter Pan', // day 349: Peter Pan
  'The Wizard of Oz', // day 350: The Wizard of Oz
  'Taxi Driver', // day 351: Taxi Driver
  'American Beauty', // day 352: American Beauty
  'Barbie', // day 353: Barbie
  'The Holiday', // day 354: The Holiday
  '2001: A Space Odyssey', // day 355: 2001: A Space Odyssey
  'Stand by Me', // day 356: Stand by Me
  'Beauty and the Beast', // day 357: Beauty and the Beast
  'The Terminator', // day 358: The Terminator
  'John Wick', // day 359: John Wick
  'The Devil Wears Prada', // day 360: The Devil Wears Prada
  'Independence Day', // day 361: Independence Day
  'I, Tonya', // day 362: I, Tonya
  '12 Angry Men', // day 363: 12 Angry Men
  'Bridesmaids', // day 364: Bridesmaids
  'Mean Girls', // day 365: Mean Girls
  'Murder on the Orient Express', // day 366: Murder on the Orient Express
];
