// Writes the curated puzzle set + tier-1 dictionary straight into
// games/quadz/ as ES modules — re-run this any time selected-366-final.json
// changes (e.g. after swapping out more flagged words) to refresh the
// shipped game files, rather than hand-editing them.
//
// Usage: node export-to-game.js

const fs = require('fs');
const path = require('path');

const GAME_DIR = path.join(__dirname, '..', '..', 'games', 'quadz');

// --- puzzles.js ---
// Just the 4 row-words per day — columns are cheap to derive at runtime
// (col[i] = rows[0][i]+rows[1][i]+rows[2][i]+rows[3][i]), so there's no
// reason to store both and risk them drifting out of sync.
const schedule = JSON.parse(fs.readFileSync(path.join(__dirname, 'selected-366-final.json'), 'utf8'));
schedule.sort((a, b) => a.day - b.day);
if (schedule.length !== 366 || schedule[0].day !== 1 || schedule[365].day !== 366) {
  throw new Error(`Expected exactly days 1-366, got ${schedule.length} entries (first=${schedule[0].day}, last=${schedule[schedule.length - 1].day})`);
}

const puzzlesBody = schedule
  .map((p) => `  [${p.rows.map((w) => `"${w}"`).join(', ')}], // day ${p.day}`)
  .join('\n');

const puzzlesJs = `// Auto-generated by tools/wordgrid-curation/export-to-game.js — do not hand-edit.
// One entry per calendar day-of-year (index 0 = day 1), each the 4 ACROSS
// words for that day's starting grid — see games/quadz/index.js for how
// the columns and the shuffled starting arrangement are derived from these.
export const PUZZLES_366 = [
${puzzlesBody}
];
`;
fs.writeFileSync(path.join(GAME_DIR, 'puzzles.js'), puzzlesJs);
console.log(`Wrote puzzles.js (${schedule.length} days)`);

// --- words.js ---
// The tier-1 "valid word" list (SCOWL, the same curated dictionary used to
// build the common-word pool) — used at runtime to accept ANY valid
// rearrangement of the 16 letters, not just the day's original words.
const scowlWords = fs.readFileSync(path.join(__dirname, 'scowl-wordlist.txt'), 'utf8')
  .split('\n')
  .map((w) => w.trim().toUpperCase())
  .filter((w) => /^[A-Z]{4}$/.test(w));
const allWords = [...new Set(scowlWords)].sort();

const wordsJs = `// Auto-generated by tools/wordgrid-curation/export-to-game.js — do not hand-edit.
// The tier-1 "valid word" list (any 4-letter word in SCOWL, the curated
// dictionary behind most spell-checkers) — used to validate ANY row/column
// arrangement the player makes, not just the day's original words. This is
// deliberately much broader than the "common word" list used to build
// puzzles.js in the first place (see tools/wordgrid-curation/ for that
// curation process) — a word doesn't have to be common to count as a win,
// it just has to be real.
export const ALL_WORDS = [
${allWords.map((w) => `  "${w}",`).join('\n')}
];
`;
fs.writeFileSync(path.join(GAME_DIR, 'words.js'), wordsJs);
console.log(`Wrote words.js (${allWords.length} words)`);
