// Compacts the rebuild's 313-slot output (with gaps at the 2 failed
// fetches) down to a gap-free sequence and writes the final answers.js.

const fs = require('fs');
const path = require('path');

const IMAGES_DIR = path.join(__dirname, '..', '..', 'games', 'muveez', 'images');
const ANSWERS_PATH = path.join(__dirname, '..', '..', 'games', 'muveez', 'answers.js');
const REBUILD_LOG = path.join(__dirname, 'rebuild-log.json');
const STAGING_DIR = path.join(__dirname, 'renumber-staging');

function main() {
  const results = JSON.parse(fs.readFileSync(REBUILD_LOG, 'utf8'));
  const survivors = results.filter((r) => r.status === 'ok');
  console.log('Survivors:', survivors.length);

  fs.rmSync(STAGING_DIR, { recursive: true, force: true });
  fs.mkdirSync(STAGING_DIR, { recursive: true });

  survivors.forEach((s, i) => {
    const newDay = i + 1;
    fs.copyFileSync(path.join(IMAGES_DIR, `${s.dayNumber}.jpg`), path.join(STAGING_DIR, `${newDay}.jpg`));
  });

  const maxOldDay = Math.max(...results.map((r) => r.dayNumber));
  for (let day = 1; day <= maxOldDay; day++) {
    const p = path.join(IMAGES_DIR, `${day}.jpg`);
    if (fs.existsSync(p)) fs.unlinkSync(p);
  }
  survivors.forEach((s, i) => {
    const newDay = i + 1;
    fs.renameSync(path.join(STAGING_DIR, `${newDay}.jpg`), path.join(IMAGES_DIR, `${newDay}.jpg`));
  });
  fs.rmSync(STAGING_DIR, { recursive: true, force: true });

  const lines = survivors.map((s, i) => {
    const day = i + 1;
    const escaped = s.title.replace(/'/g, "\\'");
    return `  '${escaped}', // day ${day}: ${s.title}`;
  });

  const fileContent = `// Auto-generated by tools/muveez-curation/finalize-rebuild.js — do not hand-edit.
// One answer per calendar day-of-year, same indexing as images/<day>.jpg
// (see index.js's dayOfYear() usage).
export const ANSWERS_366 = [
${lines.join('\n')}
];
`;
  fs.writeFileSync(ANSWERS_PATH, fileContent);
  console.log(`Done. answers.js now has ${survivors.length} entries (days 1-${survivors.length}).`);
}

main();
