// Removes specific day numbers from the current answers.js and compacts
// survivors. Generic one-off tool — reused here to remove "Toy Story 2"
// (day 364) since it's a franchise duplicate of "Toy Story" (kept).
//
// Usage: node merge-batch9.js 364

const fs = require('fs');
const path = require('path');

const IMAGES_DIR = path.join(__dirname, '..', '..', 'games', 'muveez', 'images');
const ANSWERS_PATH = path.join(__dirname, '..', '..', 'games', 'muveez', 'answers.js');
const STAGING_DIR = path.join(__dirname, 'renumber-staging');

function readCurrentAnswers() {
  const src = fs.readFileSync(ANSWERS_PATH, 'utf8');
  const match = src.match(/export const ANSWERS_366 = \[([\s\S]*)\];/);
  const titles = [];
  match[1].split('\n').forEach((line) => {
    const m = line.match(/^\s*'((?:[^'\\]|\\.)*)',/);
    if (m) titles.push(m[1].replace(/\\'/g, "'"));
  });
  return titles;
}

function main() {
  const removeSet = new Set((process.argv[2] || '').split(',').map((s) => parseInt(s.trim(), 10)).filter((n) => !isNaN(n)));
  console.log(`Removing ${removeSet.size} day(s): ${[...removeSet].sort((a, b) => a - b).join(', ')}`);

  const titles = readCurrentAnswers();
  const allDays = titles.map((title, i) => ({ day: i + 1, title }));
  const survivors = allDays.filter((d) => !removeSet.has(d.day));
  console.log(`Survivors: ${survivors.length} (was ${allDays.length})`);

  fs.rmSync(STAGING_DIR, { recursive: true, force: true });
  fs.mkdirSync(STAGING_DIR, { recursive: true });

  survivors.forEach((s, i) => {
    const newDay = i + 1;
    fs.copyFileSync(path.join(IMAGES_DIR, `${s.day}.jpg`), path.join(STAGING_DIR, `${newDay}.jpg`));
  });

  for (let day = 1; day <= allDays.length; day++) {
    const p = path.join(IMAGES_DIR, `${day}.jpg`);
    if (fs.existsSync(p)) fs.unlinkSync(p);
  }
  survivors.forEach((s, i) => {
    const newDay = i + 1;
    fs.renameSync(path.join(STAGING_DIR, `${newDay}.jpg`), path.join(IMAGES_DIR, `${newDay}.jpg`));
  });
  fs.rmSync(STAGING_DIR, { recursive: true, force: true });

  const lines = survivors.map((s, i) => {
    const day = i + 1;
    const escaped = s.title.replace(/'/g, "\\'");
    return `  '${escaped}', // day ${day}: ${s.title}`;
  });

  const fileContent = `// Auto-generated by tools/muveez-curation/merge-batch9.js — do not hand-edit.
// One answer per calendar day-of-year, same indexing as images/<day>.jpg
// (see index.js's dayOfYear() usage).
export const ANSWERS_366 = [
${lines.join('\n')}
];
`;
  fs.writeFileSync(ANSWERS_PATH, fileContent);
  console.log(`Done. answers.js now has ${survivors.length} entries (days 1-${survivors.length}).`);
}

main();
