// One-off style tool: removes a specific set of day numbers (both the image
// file AND the answer text) from the CURRENT already-compacted 1..366
// sequence, then re-compacts the survivors down to a fresh gap-free
// sequence again.
//
// IMPORTANT: unlike renumber.js (which maps a file's ORIGINAL candidates.json
// index to a title — only valid the FIRST time survivors get compacted),
// this script reads titles from the CURRENT answers.js, since after one
// round of compaction the image numbers no longer correspond to
// candidates.json's original order at all. Use this script (not
// renumber.js) for any later "remove some days and re-compact" pass.
//
// Usage: node remove-days.js 19,20,29,30,...

const fs = require('fs');
const path = require('path');

const IMAGES_DIR = path.join(__dirname, '..', '..', 'games', 'muveez', 'images');
const ANSWERS_PATH = path.join(__dirname, '..', '..', 'games', 'muveez', 'answers.js');
const STAGING_DIR = path.join(__dirname, 'renumber-staging');

function readCurrentAnswers() {
  const src = fs.readFileSync(ANSWERS_PATH, 'utf8');
  const match = src.match(/export const ANSWERS_366 = \[([\s\S]*)\];/);
  const titles = [];
  match[1].split('\n').forEach((line) => {
    const m = line.match(/^\s*'((?:[^'\\]|\\.)*)',/);
    titles.push(m ? m[1].replace(/\\'/g, "'") : '');
  });
  return titles; // index 0 = day 1
}

function main() {
  const argDays = (process.argv[2] || '').split(',').map((s) => parseInt(s.trim(), 10)).filter((n) => !isNaN(n));
  const removeSet = new Set(argDays);
  console.log(`Removing ${removeSet.size} unique day(s): ${[...removeSet].sort((a, b) => a - b).join(', ')}`);

  const titles = readCurrentAnswers();

  // Only days 1..366 are considered here — any spare files beyond 366
  // (leftover unused fetches) are left completely untouched, since we have
  // no recorded title for them to safely carry forward.
  const survivors = [];
  for (let day = 1; day <= titles.length; day++) {
    if (!removeSet.has(day)) survivors.push({ oldDay: day, title: titles[day - 1] });
  }

  console.log(`Survivors: ${survivors.length} (was ${titles.length})`);

  // Stage renamed copies first so an old day's file is never overwritten
  // before it's been read.
  fs.rmSync(STAGING_DIR, { recursive: true, force: true });
  fs.mkdirSync(STAGING_DIR, { recursive: true });

  survivors.forEach((s, i) => {
    const newDay = i + 1;
    const srcPath = path.join(IMAGES_DIR, `${s.oldDay}.jpg`);
    fs.copyFileSync(srcPath, path.join(STAGING_DIR, `${newDay}.jpg`));
  });

  // Delete every day-1..366 file (removed ones AND survivors, since
  // survivors have already been safely copied into staging), then move the
  // staged (renumbered) survivors into place. Spares beyond 366 are never
  // touched.
  for (let day = 1; day <= titles.length; day++) {
    const p = path.join(IMAGES_DIR, `${day}.jpg`);
    if (fs.existsSync(p)) fs.unlinkSync(p);
  }
  survivors.forEach((s, i) => {
    const newDay = i + 1;
    fs.renameSync(path.join(STAGING_DIR, `${newDay}.jpg`), path.join(IMAGES_DIR, `${newDay}.jpg`));
  });
  fs.rmSync(STAGING_DIR, { recursive: true, force: true });

  const lines = survivors.map((s, i) => {
    const newDay = i + 1;
    const escaped = s.title.replace(/'/g, "\\'");
    return `  '${escaped}', // day ${newDay}: ${s.title}`;
  });

  const fileContent = `// Auto-generated by tools/muveez-curation/remove-days.js — do not hand-edit.
// One answer per calendar day-of-year, same indexing as images/<day>.jpg
// (see index.js's dayOfYear() usage).
export const ANSWERS_366 = [
${lines.join('\n')}
];
`;
  fs.writeFileSync(ANSWERS_PATH, fileContent);

  console.log(`Done. answers.js now has ${survivors.length} real answers (days 1-${survivors.length}).`);
  if (survivors.length < 366) {
    console.log(`Days ${survivors.length + 1}-366 have no answer yet — placeholder fallback will show until more are added.`);
  }
}

main();
