// Run this AFTER manually deleting unwanted images from games/muveez/images/
// (following fetch-all.js's batch download, which numbered them 1..450
// matching candidates.json's order). Whatever numbered .jpg files remain
// get compacted down to a gap-free 1..N sequence (so e.g. if 2.jpg and
// 5.jpg were deleted, survivors 1,3,4,6,7... become 1,2,3,4,5...), and
// games/muveez/answers.js is regenerated to match — each survivor's title
// (looked up from its ORIGINAL number in candidates.json, before
// renumbering) follows its image to the new number.
//
// Files renamed via a temp staging directory rather than in-place, so there's
// no risk of one rename overwriting a file that hasn't been processed yet.
//
// Usage: node renumber.js

const fs = require('fs');
const path = require('path');

const CANDIDATES_PATH = path.join(__dirname, 'candidates.json');
const IMAGES_DIR = path.join(__dirname, '..', '..', 'games', 'muveez', 'images');
const ANSWERS_PATH = path.join(__dirname, '..', '..', 'games', 'muveez', 'answers.js');
const STAGING_DIR = path.join(__dirname, 'renumber-staging');

function main() {
  const data = JSON.parse(fs.readFileSync(CANDIDATES_PATH, 'utf8'));

  const survivors = fs.readdirSync(IMAGES_DIR)
    .map((f) => {
      const m = f.match(/^(\d+)\.jpg$/);
      return m ? { file: f, oldNumber: parseInt(m[1], 10) } : null;
    })
    .filter(Boolean)
    .sort((a, b) => a.oldNumber - b.oldNumber);

  if (survivors.length === 0) {
    console.log('No numbered images found in', IMAGES_DIR);
    return;
  }

  console.log(`Found ${survivors.length} surviving images (out of ${data.candidates.length} originally fetched).`);

  // Stage renamed copies first so an old number's file is never overwritten
  // before it's been read (see the file header for why this matters).
  fs.rmSync(STAGING_DIR, { recursive: true, force: true });
  fs.mkdirSync(STAGING_DIR, { recursive: true });

  const renumbered = survivors.map((s, i) => {
    const newNumber = i + 1;
    const title = data.candidates[s.oldNumber - 1] ? data.candidates[s.oldNumber - 1].title : '';
    fs.copyFileSync(path.join(IMAGES_DIR, s.file), path.join(STAGING_DIR, `${newNumber}.jpg`));
    return { newNumber, oldNumber: s.oldNumber, title };
  });

  // Clear out the old numbered files, then move the staged (renumbered)
  // ones into their place.
  survivors.forEach((s) => fs.unlinkSync(path.join(IMAGES_DIR, s.file)));
  renumbered.forEach((r) => {
    fs.renameSync(path.join(STAGING_DIR, `${r.newNumber}.jpg`), path.join(IMAGES_DIR, `${r.newNumber}.jpg`));
  });
  fs.rmSync(STAGING_DIR, { recursive: true, force: true });

  // answers.js only has 366 real slots (dayOfYear() never exceeds 366) —
  // anything beyond that survived on disk but won't ever be shown in-game.
  const usable = renumbered.filter((r) => r.newNumber <= 366);
  const overflow = renumbered.length - usable.length;
  const maxDay = usable.length ? Math.max(...usable.map((r) => r.newNumber)) : 0;

  const lines = [];
  for (let day = 1; day <= maxDay; day++) {
    const entry = usable.find((r) => r.newNumber === day);
    const title = entry ? entry.title.replace(/'/g, "\\'") : '';
    lines.push(`  '${title}',${entry ? ` // day ${day}: ${entry.title}` : ` // day ${day}: not yet assigned`}`);
  }

  const fileContent = `// Auto-generated by tools/muveez-curation/renumber.js — do not hand-edit.
// One answer per calendar day-of-year, same indexing as images/<day>.jpg
// (see index.js's dayOfYear() usage).
export const ANSWERS_366 = [
${lines.join('\n')}
];
`;
  fs.writeFileSync(ANSWERS_PATH, fileContent);

  console.log(`Renumbered ${renumbered.length} images to 1..${renumbered.length}.`);
  console.log(`answers.js written with ${usable.length} real answers (days 1-${maxDay}).`);
  if (overflow > 0) {
    console.log(`Note: ${overflow} image(s) numbered 367+ survived but are unused by the game (day-of-year never exceeds 366) — left on disk as spares, not deleted.`);
  }
  if (maxDay < 366) {
    console.log(`Note: days ${maxDay + 1}-366 have no answer yet and will show the placeholder fallback until more are added.`);
  }
}

main();
