// Step 2 of the curation loop: commits whatever decision was made about the
// candidate that next.js most recently prepared (see pending-review.json).
//
//   node resolve.js accept   -> copies preview.jpg into the real game's
//                                images/ folder as the next day number,
//                                regenerates answers.js from all accepted
//                                candidates so far, marks this candidate
//                                'added' in candidates.json, advances
//                                nextDay.
//   node resolve.js skip     -> marks this candidate 'skipped', nothing
//                                else changes (nextDay stays put, no image
//                                or answer is written).
//
// Either way, candidates.json is the single source of truth for what's
// been decided — running `node next.js` again afterward automatically picks
// up the NEXT 'pending' candidate, which is what makes this resumable
// across separate chat sessions: as long as candidates.json is on disk,
// nobody has to remember where they left off.

const fs = require('fs');
const path = require('path');

const CANDIDATES_PATH = path.join(__dirname, 'candidates.json');
const PENDING_REVIEW_PATH = path.join(__dirname, 'pending-review.json');
const PREVIEW_PATH = path.join(__dirname, 'preview.jpg');
const IMAGES_DIR = path.join(__dirname, '..', '..', 'games', 'muveez', 'images');
const ANSWERS_PATH = path.join(__dirname, '..', '..', 'games', 'muveez', 'answers.js');

function regenerateAnswersFile(candidates) {
  const added = candidates.filter((c) => c.status === 'added').sort((a, b) => a.day - b.day);
  const maxDay = added.length ? Math.max(...added.map((c) => c.day)) : 0;
  // Fills every day 1..maxDay — any day not yet assigned a movie (still
  // pending future review) gets an empty string placeholder rather than
  // shifting later days down, so day numbers stay stable as more get added.
  const lines = [];
  for (let day = 1; day <= maxDay; day++) {
    const entry = added.find((c) => c.day === day);
    const title = entry ? entry.title.replace(/'/g, "\\'") : '';
    lines.push(`  '${title}',${entry ? ` // day ${day}: ${entry.title} (${entry.year})` : ` // day ${day}: not yet assigned`}`);
  }

  const fileContent = `// Auto-generated by tools/muveez-curation/resolve.js — do not hand-edit.
// One answer per calendar day-of-year, same indexing as images/<day>.jpg
// (see index.js's dayOfYear() usage). Regenerated from scratch every time a
// new candidate is accepted, so it always reflects tools/muveez-curation/
// candidates.json exactly — edit candidates.json (or run the curation loop
// again) rather than editing this file directly.
export const ANSWERS_366 = [
${lines.join('\n')}
];
`;
  fs.writeFileSync(ANSWERS_PATH, fileContent);
}

function main() {
  const action = process.argv[2];
  if (action !== 'accept' && action !== 'skip') {
    console.error('Usage: node resolve.js <accept|skip>');
    process.exit(1);
  }
  if (!fs.existsSync(PENDING_REVIEW_PATH)) {
    console.error('No pending-review.json found — run next.js first.');
    process.exit(1);
  }

  const pending = JSON.parse(fs.readFileSync(PENDING_REVIEW_PATH, 'utf8'));
  const data = JSON.parse(fs.readFileSync(CANDIDATES_PATH, 'utf8'));
  const candidate = data.candidates[pending.index];

  if (!candidate || candidate.title !== pending.title) {
    console.error('candidates.json has changed since next.js ran — refusing to resolve a stale review.');
    process.exit(1);
  }

  if (action === 'skip') {
    candidate.status = 'skipped';
    fs.writeFileSync(CANDIDATES_PATH, JSON.stringify(data, null, 2));
    fs.unlinkSync(PENDING_REVIEW_PATH);
    console.log(`Skipped "${candidate.title}" (${candidate.year}).`);
    return;
  }

  // accept
  const day = data.nextDay;
  fs.mkdirSync(IMAGES_DIR, { recursive: true });
  fs.copyFileSync(PREVIEW_PATH, path.join(IMAGES_DIR, `${day}.jpg`));

  candidate.status = 'added';
  candidate.day = day;
  candidate.tmdbId = pending.tmdbId;
  candidate.sourceUrl = pending.sourceUrl;
  data.nextDay = day + 1;

  fs.writeFileSync(CANDIDATES_PATH, JSON.stringify(data, null, 2));
  regenerateAnswersFile(data.candidates);
  fs.unlinkSync(PENDING_REVIEW_PATH);
  console.log(`Added "${candidate.title}" (${candidate.year}) as day ${day}. Next day will be ${data.nextDay}.`);
}

main();
