// One-off random shuffle of the day ordering — requested so that similar
// movies (e.g. a run of Disney animated classics) aren't clustered together
// on consecutive calendar days. Image file bytes and titles move together
// (same permutation applied to both), so the pairing stays correct; only
// WHICH day number each movie lands on changes, and it's true randomness
// (Math.random(), not a seeded shuffle) since this is meant to run once,
// not regenerate the same "random" order every time.
//
// Usage: node shuffle-days.js

const fs = require('fs');
const path = require('path');

const IMAGES_DIR = path.join(__dirname, '..', '..', 'games', 'muveez', 'images');
const ANSWERS_PATH = path.join(__dirname, '..', '..', 'games', 'muveez', 'answers.js');
const STAGING_DIR = path.join(__dirname, 'renumber-staging');

function readCurrentAnswers() {
  const src = fs.readFileSync(ANSWERS_PATH, 'utf8');
  const match = src.match(/export const ANSWERS_366 = \[([\s\S]*)\];/);
  const titles = [];
  match[1].split('\n').forEach((line) => {
    const m = line.match(/^\s*'((?:[^'\\]|\\.)*)',/);
    if (m) titles.push(m[1].replace(/\\'/g, "'"));
  });
  return titles;
}

// Fisher-Yates shuffle.
function shuffle(array) {
  const result = array.slice();
  for (let i = result.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [result[i], result[j]] = [result[j], result[i]];
  }
  return result;
}

function main() {
  const titles = readCurrentAnswers();
  const n = titles.length;
  console.log('Shuffling', n, 'days...');

  const oldDayOrder = shuffle(Array.from({ length: n }, (_, i) => i + 1)); // oldDayOrder[i] = which old day now becomes new day i+1

  fs.rmSync(STAGING_DIR, { recursive: true, force: true });
  fs.mkdirSync(STAGING_DIR, { recursive: true });

  oldDayOrder.forEach((oldDay, i) => {
    const newDay = i + 1;
    fs.copyFileSync(path.join(IMAGES_DIR, `${oldDay}.jpg`), path.join(STAGING_DIR, `${newDay}.jpg`));
  });

  for (let day = 1; day <= n; day++) {
    fs.unlinkSync(path.join(IMAGES_DIR, `${day}.jpg`));
  }
  oldDayOrder.forEach((oldDay, i) => {
    const newDay = i + 1;
    fs.renameSync(path.join(STAGING_DIR, `${newDay}.jpg`), path.join(IMAGES_DIR, `${newDay}.jpg`));
  });
  fs.rmSync(STAGING_DIR, { recursive: true, force: true });

  const lines = oldDayOrder.map((oldDay, i) => {
    const newDay = i + 1;
    const title = titles[oldDay - 1];
    const escaped = title.replace(/'/g, "\\'");
    return `  '${escaped}', // day ${newDay}: ${title}`;
  });

  const fileContent = `// Auto-generated by tools/muveez-curation/shuffle-days.js — do not hand-edit.
// One answer per calendar day-of-year, same indexing as images/<day>.jpg
// (see index.js's dayOfYear() usage). Day order was randomly shuffled once
// so similar movies (e.g. consecutive Disney classics) aren't clustered on
// consecutive calendar days.
export const ANSWERS_366 = [
${lines.join('\n')}
];
`;
  fs.writeFileSync(ANSWERS_PATH, fileContent);
  console.log('Done. answers.js and images/ rewritten in shuffled order.');
}

main();
